version: '3.8'
services:
  sca-integrator-svc:
    image: ${URL_REGISTRY}/i3gis-registry/sca-integrator:latest
    container_name: sca-integrator-service
    restart: always
    env_file:
      - /var/lib/jenkins/deployment/.env
    ports:
      - '8082:8082'
    volumes:
      - "jenkins_data:/root/_project-repository/workspace:rw"
      - "sca-integrator-service-result-files:/root/_scanned-project-files"
      - "cache_data:/root/.cache/"
    environment:
        APP_ENV: "development"
        DB_HOST: ${PG_HOST}
        DB_USER: ${PG_USERNAME}
        DB_PASSWORD: ${PG_PASSWORD_GOLANG}
        DB_PORT: ${PG_PORT}
        DB_NAME: "sca_integrator"
        APP_PORT: "8082"
        TRIVY_SERVER_URL: "http://trivy-server:8069"
        TRIVY_TIMEOUT: "5m"
        PREFIX_PROJECT_FOLDER: "/_project-repository/workspace/"
        PREFIX_RESULT_FOLDER: "/_scanned-project-files/"
    networks:
        - i3gis-net
networks:
  i3gis-net:
    external: true
